Blazored/Modal

- README.md
- samples/BlazorSample/Pages/Index.cshtml
- src/Blazored.Modal/BlazoredModal.cshtml.cs
- src/Blazored.Modal/Services/ModalService.cs
Fixes #2 
This PR correctly fires the OnClose event on the ModalService when the modal closes. Developers can now attach a handler to this event and it will be called when the modal closes.
> Exposes OnClose event for modal

- README.md
- samples/BlazorSample/Pages/BackGroundCancel.razor
- samples/BlazorSample/Pages/CustomStyle.razor
- samples/BlazorSample/Pages/HideCloseButton.razor
- samples/BlazorSample/Pages/Index.razor
- samples/BlazorSample/Pages/Position.razor
- samples/BlazorSample/Pages/YesNoPrompt.razor
- samples/BlazorSample/Shared/CustomModalLayout.razor
- samples/BlazorSample/Shared/NavMenu.razor
- samples/BlazorSample/wwwroot/css/site.css
- samples/ServerSideblazor/Pages/BackGroundCancel.razor
- samples/ServerSideblazor/Pages/CustomStyle.razor
- samples/ServerSideblazor/Pages/HideCloseButton.razor
- samples/ServerSideblazor/Pages/Index.razor
- samples/ServerSideblazor/Pages/Position.razor
- samples/ServerSideblazor/Pages/YesNoPrompt.razor
- samples/ServerSideblazor/Shared/CustomModalLayout.razor
- samples/ServerSideblazor/Shared/NavMenu.razor
- samples/ServerSideblazor/wwwroot/css/site.css
- src/Blazored.Modal/BlazoredModal.razor
- src/Blazored.Modal/BlazoredModal.razor.cs
- src/Blazored.Modal/ModalOptions.cs
- src/Blazored.Modal/Services/IModalService.cs
- src/Blazored.Modal/Services/ModalService.cs
- src/Blazored.Modal/wwwroot/blazored-modal.css
Adds a parameter to the `Modal.Show()` method, allowing the developer to specify a custom style for the modal.
Fixes #43
> Add parameter for custom styling

- README.md
- samples/BlazorSample/Pages/CloseSource.razor
- samples/BlazorSample/Shared/NavMenu.razor
- samples/ServerSideblazor/Pages/CloseSource.razor
- samples/ServerSideblazor/Shared/NavMenu.razor
- src/Blazored.Modal/Services/ModalResult.cs
- src/Blazored.Modal/Services/ModalService.cs
This commit could potentially fix issue #76. I don't know if you think this is a good solution, but than at least we have a starting point. I have only made the change and not made any examples for it yet. I can do this in the future, but for now I would like to see if you like this change I made.
The type of the modal that was used to show the modal will be returned in the ModalResult of the OnClose event. This way a page that has multiple components could see which component was just closed.
Again, I am not saying this is a perfect solution, just something I thought of that could be a good idea for issue #76. Just let me know what you think.
> Add parameter to ModalResult that identifies the modal which caused the close event

- src/Blazored.Modal/Services/ModalService.cs
I think this is a good fix for #91. It also seems trivial enough that there doesn't have to be an example, but let me know if you disagree.
Like you said, the ModalResult can either just be discarded, or it can be used to determine which Modal caused the Close event.
Let me know if you agree with me.
> New Close() overload

- README.md
Just a very small update, changes the HTML formatting in the readme to razor formatting. I see the razor formatting doesn't (yet) detect all the @xxxx pieces, especially when it is like this: "@xxx", but I think it is better than just html formatting.
> Change HTML to Razor language in markdown

- docs/src/customisation-options/toc.yml
- docs/src/getting-started/toc.yml
- docs/src/usage/long-running-task.md
- docs/src/usage/toc.yml
- samples/BlazorServer/Pages/LongRunningTask.razor
- samples/BlazorServer/Shared/Loading.razor
- samples/BlazorServer/Shared/NavMenu.razor
- samples/BlazorWebAssembly/Pages/LongRunningTask.razor
- samples/BlazorWebAssembly/Shared/Loading.razor
- samples/BlazorWebAssembly/Shared/NavMenu.razor
- src/Blazored.Modal/BlazoredModal.razor.cs
- src/Blazored.Modal/ModalReference.cs
- src/Blazored.Modal/Services/IModalService.cs
- src/Blazored.Modal/Services/ModalService.cs
This PR closes #120. It adds a `Close()` function to `ModalReference`. Optionally a `ModalResult` can be passed, which I think is handy when having a long-running task that can give some result. 
I added an example that shows the loading dialog while waiting for 5 seconds, as I think this is what people were trying to make in #120.
I added a new function to the `ModalService `that can close a modal using the `ModalReference `instead of the `ModalReference.Id`. The reasoning for this function is because I wanted to keep the arguments used between the `OnModalInstanceAdded` and `OnModalCloseRequested` the same in the `ModalService`. I can understand though if we would rather just use the functions that use the `ModalReference.Id`. Just let me know!
> Closing modal using ModalReference

- src/Blazored.Modal/IModalReference.cs
- src/Blazored.Modal/ModalReference.cs
- src/Blazored.Modal/Services/IModalService.cs
- src/Blazored.Modal/Services/ModalService.cs
Resolves #170 
The `ModalService` now returns an `IModalReference` instead of the concrete `ModalReference` type.
> Modal service now returns IModalReference instead of ModalReference

- samples/BlazorServer/Pages/CustomLayout.razor
- samples/BlazorServer/Shared/CustomBootstrapModal.razor
- samples/BlazorServer/Shared/NavMenu.razor
- samples/BlazorWebAssembly/Pages/CustomLayout.razor
- samples/BlazorWebAssembly/Shared/CustomBootstrapModal.razor
- samples/BlazorWebAssembly/Shared/NavMenu.razor
- src/Blazored.Modal/BlazoredModal.razor.cs
- src/Blazored.Modal/BlazoredModalInstance.razor
- src/Blazored.Modal/BlazoredModalInstance.razor.cs
- src/Blazored.Modal/Configuration/ModalOptions.cs
- src/Blazored.Modal/package-lock.json
Hi,
This is an option to use custom layout for modals. Resolves #167.
I have implemented a `ModalOptions.UseCustomLayout` property. If you set this to `true` it replaces the whole content of the `BlazoredModalInstance` with the `Component` you use.
Cheers,
dfkeenan
> Adds the ability to provide custom layouts for the modal such as Bootstrap 

- src/Blazored.Modal/BlazoredModal.razor.cs
Resolves #212
When navigating from a page when a modal window is open, the focus trap prevents user from interacting with the page.
By invoking the deactivateFocusTrap method, the web now works as intended.
> Focus traps are now deactivated when navigating from page

- src/Blazored.Modal/BlazoredModal.razor.cs
- src/Blazored.Modal/BlazoredModalInstance.razor
- src/Blazored.Modal/Configuration/ModalReference.cs
- src/Blazored.Modal/Services/ModalService.cs
- tests/src/Blazored.Modal.Tests/DisplayTests.cs
This changes the behavior of the `BlazoredModal` `.CloseInstance` and `.CancelInstance` methods to "gracefully" close the modal by calling the `BlazoredModalInstance.Close` method instead if just dismissing it.
This allows the configured animations (and future features) to also work when a close is requested programmatically from the returned `ModalReference`.
To achieve this a reference to the displayed `BlazoredModalInstance` had to be captured, and is stored internally in `ModalReference`.
> Gracefully close modal when close is called

- samples/BlazorWebAssembly/Pages/NavigateAfterModal.razor
- samples/BlazorWebAssembly/Shared/NavMenu.razor
- src/Blazored.Modal/BlazoredModal.razor.cs
This should fix #230. It does so by calling `.ToList()` on the list in `CancelModals` and looping over that. This way, if the underlying collection changes during the loop, it won't cause an exception here.
I am not sure this is the best solution. If the underlying collection changes while looping over it, maybe we should catch this using `try { ... } catch() { ... } and loop again over the changed collection so that all items in the collection are removed, even when one is added midway trough removing them. I made this PR just so we can look at a possible solution, but I am not convinced yet this is really the best solution. Would love to hear what your opinions are on this.
> [Bugfix] Navigate Away

- src/Blazored.Modal/BlazoredModalInstance.razor
- src/Blazored.Modal/BlazoredModalInstance.razor.cs
> [Bugfix] Fixes representation of animation duration when the current culture doesn't use a period as the decimal separator

- src/Blazored.Modal/Interop/Blazored.Modal.ts
This is commit, adds `allowOutsideClick: () => true` in to Blazored.Modal.ts which should fix #224  (and fix #217 and fix #236).
The reason I've used a function that returns true `:() => true` instead of just setting it `:true`, is that Blazored.Modal is not using the latest version of "focus-trap" library. 
`allowOutsideClick` property in Blazored-Modal currently:
```
allowOutsideClick?: (event: MouseEvent) => boolean;
```
`allowOutsideClick` property in current version of focus-trap library:
```
allowOutsideClick?: boolean | MouseEventToBoolean;
```
Updating focus-trap should solve this, but this works for now.
>  Added allowOutsideClick to capture clicks outside the focus trap

- src/Blazored.Modal/BlazoredModalInstance.razor
- src/Blazored.Modal/BlazoredModalInstance.razor.cs
This PR fixes #211 by implementing the correct `aria-label` for the close button, allowing the user to tab to the close button, and adding the correct role to the Modal itself.
Re-enabling the tabindex on the close button caused the FocusTrap to autofocus the close button each time the modal was opened. I really didn't like this behavior, and have implemented a fix for this by applying setting the tabindex to -1 at first, and only removing it after the FocusTrap is activated. This way the close button is not autofocused, but it is focusable.
> Add basic ARIA attributes to modal

- README.md
Currently links directly to the images
> Link to Nuget and Build Status in readme badges

- src/Blazored.Modal/BlazoredModalInstance.razor.cs
- src/Blazored.Modal/Configuration/ModalOptions.cs
Hello,
I am a user of your library. I had a use case, where I needed to disable the auto focus to the first element. 
I figure not everyone would like that to happen. Added boolean FocusFirstElement to the options. Left auto focus as default.
Keep up the good work Chris!
> Able to optionally set focus to first element to false

- README.md
- samples/BlazorServer/Shared/Confirm.razor
- samples/BlazorServer/Shared/CustomBootstrapModal.razor
- samples/BlazorServer/Shared/DisplayMessage.razor
- samples/BlazorServer/Shared/FullContentPage.razor
- samples/BlazorServer/Shared/MessageForm.razor
- samples/BlazorServer/Shared/YesNoPrompt.razor
- samples/BlazorServer/Shared/YesNoPromptAnimation.razor
- samples/BlazorWebAssembly/Shared/Confirm.razor
- samples/BlazorWebAssembly/Shared/CustomBootstrapModal.razor
- samples/BlazorWebAssembly/Shared/DisplayMessage.razor
- samples/BlazorWebAssembly/Shared/FullContentPage.razor
- samples/BlazorWebAssembly/Shared/MessageForm.razor
- samples/BlazorWebAssembly/Shared/YesNoPrompt.razor
- samples/BlazorWebAssembly/Shared/YesNoPromptAnimation.razor
- src/Blazored.Modal/BlazoredModal.razor.cs
- src/Blazored.Modal/BlazoredModalInstance.razor
- src/Blazored.Modal/BlazoredModalInstance.razor.cs
- tests/src/Blazored.Modal.Tests/Assets/TestComponent.razor
Hello,
Submiting this PR since, the **PR**:
#207  --> "Renamed BlazoredModalInstance Close and Cancel methods with Async suffix #207"
seems to have gone stale and I already had this sitting on my forked repo.
> #206 | Renamed BlazoredModalInstance Close and Cancel to CloseAsync and CancelAsync

- samples/BlazorServer/Shared/CustomBootstrapModal.razor
This pr closes #266. It does so by moving the backdrop into the modal (so the click event is properly registered to the backdrop but NOT to the modal itself). It also hooks up the close button in the header of the modal.
> [bugfix] Bootstrap custom modal background clicks

- src/Blazored.Modal/tsconfig.json
This pr fixes #228 by changing the generated javascript from ES2019 to ES5. This shouldn't break any existing behavior, and the quick check I did in chrome confirms it doesn't (or atleast, all samples still work).
> Change generated javascript to enable IE11 usage again

- src/Blazored.Modal/BlazoredModal.razor.cs
- src/Blazored.Modal/BlazoredModalInstance.razor.cs
- src/Blazored.Modal/CascadingBlazoredModal.razor
- src/Blazored.Modal/Configuration/ModalOptions.cs
> Change FocusFirstElement to ActivateFocusTrap

- samples/BlazorServer/Pages/PassDataToModal.razor
- samples/BlazorWebAssembly/Pages/PassDataToModal.razor
- src/Blazored.Modal/Configuration/ModalParameters.cs
This PR Closes #373
- Implemented `IEnumerable` that exposes the underlying dictionary enumerator, which enables the use of collection initializers.
- Updated samples to use initializer.
- Fixed/updated code-section of the samples to match.
> Collection initialization support for ModalParameters

- src/Blazored.Modal/Configuration/ModalParameters.cs
small PR that updates the `Add` method to return the instance of `ModalParameters`, so that this:
```csharp
var parameters = new ModalParameters();
parameters.Add("Name", "My Name");
parameters.Add("Number", 42);
```
can also be written as:
```csharp
var parameters = new ModalParameters()
.Add("Name", "My Name")
.Add("Number", 42);
```
> fluent "add" for modal parameters

- src/Blazored.Modal/BlazoredModalInstance.razor
- src/Blazored.Modal/BlazoredModalInstance.razor.cs
Hi Chris,
I've got custom dialogs in my setup and was having trouble with the preview packages. These tweaks sorted it for me. 
Null check on FocusTrap in OnAfterRenderAsync
* If using custom dialogs _focusTrap is not set but there's no null check on the render 
Make FocusTrap field public so it can be used in custom dialogs
* Changing to public means we can add FocusTrap in custom dialogs if we want to (and the null ref check prevents errors if we don't) 
* Renamed _focusTrap to FocusTrap and set the variable annotation as nullable
I was tempted to change
```
private void AttemptFocus() 
=> _setFocus = FocusTrap != null;
```
But wasn't sure if there's a time before the first render when the @ref gets set that AttemptFocus might be called
Cheers,
Danny
> Proposed tweaks for FocusTrap

- src/Blazored.Modal/BlazoredModalInstance.razor
- src/Blazored.Modal/BlazoredModalInstance.razor.cs
Mouse click, down, and up events will be handled to avoid closing the modal by accident. This avoids accidents when highlighting text and dragging the mouse cursor outside of the modal area (into the background).
Solves #518
This also allows the user to escape closing the modal by dragging the mouse click back into the modal content area.
> Control background click mouse events

- src/Blazored.Modal/BlazoredModal.razor.js
Currently, if someone uses a class to apply an `overflow` value to the `body`, the value won't be reset to default in `removeBodyStyle`.
This way, the current computed value is used.
> Use computed style to consider the real values
