Blazored/Modal

README.md
samples/BlazorSample/Pages/Index.cshtml
samples/BlazorSample/Pages/SignUpForm.cshtml
src/Blazored.Modal/Blazored.Modal.csproj
src/Blazored.Modal/BlazoredModal.cshtml
src/Blazored.Modal/BlazoredModal.cshtml.cs
src/Blazored.Modal/ModalParameters.cs
src/Blazored.Modal/Services/IModalService.cs
src/Blazored.Modal/Services/ModalService.cs

- Parameters can now be passed into modal components via cascading parameter
- Tidied up APIs
- Updated README examples

Pass parameters to modal components

---

README.md

For easy quickstart so ModalParameters is already available

small addition @using Blazored.Modal

---

samples/BlazorSample/Pages/SignUpForm.cshtml
src/Blazored.Modal/Blazored.Modal.csproj
src/Blazored.Modal/BlazoredModal.cshtml.cs
src/Blazored.Modal/Services/IModalService.cs
src/Blazored.Modal/Services/ModalService.cs

Hi @chrissainty i have taken the liberty to expose Close inside ModalService so we can for example add a cancel button, if you like it you can take it.
Let me know if i need to fix something and if i should bump the version before merging.

Expose ModalService.Close

---

src/Blazored.Modal/Blazored.Modal.csproj
src/Blazored.Modal/Services/ModalService.cs

This will enable to use components that have logics in a "code behind" class via inherits. I have already bumped the version :)

Enable code behind

---

samples/BlazorSample/BlazorSample.csproj
src/Blazored.Modal/Blazored.Modal.csproj

This PR updates the projects to preview 5 of ASP.NET Core 3

project upgrade to preview 5

---

azure-pipelines.yml
samples/BlazorSample/App.razor
samples/BlazorSample/BlazorSample.csproj
samples/BlazorSample/_Imports.razor
samples/ServerSideblazor/App.razor
samples/ServerSideblazor/_Imports.razor
src/Blazored.Modal/Blazored.Modal.csproj
src/Blazored.Modal/BlazoredModal.razor

Just updated References and usings to work for Preview9.

Upgrade to Preview 9

---

README.md
samples/ServerSideblazor/Pages/Index.razor
src/Blazored.Modal/Services/IModalService.cs
src/Blazored.Modal/Services/ModalService.cs

Basic implementation of Issue #51

Implement generic Show method option

---

samples/ServerSideblazor/Pages/_Host.cshtml

Change render component as per new Blazor server updates for .net core 3.0
ref: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/#comment-800

Change render component as per new Blazor server updates

---

samples/BlazorServer/Pages/BackgroundCancel.razor
samples/BlazorServer/Pages/CustomStyle.razor
samples/BlazorServer/Pages/HideCloseButton.razor
samples/BlazorServer/Pages/Index.razor
samples/BlazorServer/Pages/PassDataToModal.razor
samples/BlazorServer/Pages/Position.razor
samples/BlazorServer/Pages/ReturnDataFromModal.razor
samples/BlazorWebAssembly/Pages/BackGroundCancel.razor
samples/BlazorWebAssembly/Pages/CustomStyle.razor
samples/BlazorWebAssembly/Pages/HideCloseButton.razor
samples/BlazorWebAssembly/Pages/Index.razor
samples/BlazorWebAssembly/Pages/PassDataToModal.razor
samples/BlazorWebAssembly/Pages/Position.razor
samples/BlazorWebAssembly/Pages/ReturnDataFromModal.razor

Fix for #128 
- changed **p** to **div**
- added **mb-4** to allow for padding

Fix for #128

---

docs/src/docfx.json

Fixes #127 
Set _gitContribute setting in docfx.json

Fixes "Improve this Doc" link

---

README.md
samples/BlazorServer/Pages/Position.razor
samples/BlazorServer/wwwroot/css/site.css
samples/BlazorWebAssembly/Pages/Position.razor
samples/BlazorWebAssembly/wwwroot/css/site.css
src/Blazored.Modal/BlazoredModalInstance.razor.cs
src/Blazored.Modal/Configuration/ModalOptions.cs
src/Blazored.Modal/Configuration/ModalPosition.cs
tests/src/Blazored.Modal.Tests/ModalOptionsTests.cs

This PR is essentially the work done by @pablopioli with some minor tweaks due to recent changes. 
Resolves #146

Allows developers to customise the position of the modal

---

samples/BlazorServer/Pages/CustomOverlay.razor
samples/BlazorServer/Shared/NavMenu.razor
samples/BlazorServer/wwwroot/css/site.css
samples/BlazorWebAssembly/Pages/CustomOverlay.razor
samples/BlazorWebAssembly/Shared/NavMenu.razor
samples/BlazorWebAssembly/wwwroot/css/site.css
src/Blazored.Modal/BlazoredModal.razor.cs
src/Blazored.Modal/BlazoredModalInstance.razor
src/Blazored.Modal/BlazoredModalInstance.razor.cs
src/Blazored.Modal/CascadingBlazoredModal.razor
src/Blazored.Modal/Configuration/ModalOptions.cs

Adds ability to define a custom overlay class

---

src/Blazored.Modal/BlazoredModal.razor.cs
src/Blazored.Modal/BlazoredModalInstance.razor.cs
src/Blazored.Modal/CascadingBlazoredModal.razor

This PR fixes #256 and some more. I found some other options which also seemed to be missing from the `GlobalOptions` and/or the `CascadingBlazoredModal`.

Adds missing options to GlobalOptions

---

README.md

This PR fixes #263. I think this should tackle everything raised in that issue, but otherwise this is a good starting point at lesat.

Change BlazoredModel to ModalInstance in readme to avoid confusion

---

src/Blazored.Modal/Services/IModalService.cs
src/Blazored.Modal/Services/ModalService.cs

Change ComponentBase to IComponent

---

src/Blazored.Modal/BlazoredModal.razor.cs
src/Blazored.Modal/Interop/Blazored.Modal.ts

Detect multiple modals on deactiveFocusTrap

---

src/Blazored.Modal/BlazoredModalInstance.razor
src/Blazored.Modal/BlazoredModalInstance.razor.cs

This PR is a proposal that applies the fade in/out animations to the modal overlay as described in issue #369
Closes #369

Add selected animations to overlay

---

src/Blazored.Modal/BlazoredModalInstance.razor
src/Blazored.Modal/BlazoredModalInstance.razor.cs
src/Blazored.Modal/Services/ModalResult.cs

Added Confirmed property to ModalResult and added payload overload to ModalResult.Cancelled

---

samples/BlazorServer/Pages/_Layout.cshtml
samples/BlazorServer/Shared/NavMenu.razor
samples/BlazorWebAssembly/Shared/NavMenu.razor

- Removed duplicate and redundant menu items. 
- Added reference to library CSS to Blazor Server sample
resolves #395

Fixes for sample projects

---

src/Blazored.Modal/CascadingBlazoredModal.razor

Added Fixed=true to cascaded blazored modal service

---

src/Blazored.Modal/Configuration/ModalReference.cs

Added TaskCreationOptions.RunContinuationsAsynchronously to ModalRefence

---

src/Blazored.Modal/BlazoredModal.razor

Added null checks for JS interop calls

---

samples/BlazorWebAssembly/wwwroot/css/app.css
src/Blazored.Modal/BlazoredModalInstance.razor
src/Blazored.Modal/BlazoredModalInstance.razor.css
tests/Blazored.Modal.Tests/DisplayTests.cs
tests/Blazored.Modal.Tests/ModalOptionsTests.cs

Prefixed CSS classes with bm

---

src/Blazored.Modal/BlazoredModal.razor
src/Blazored.Modal/Services/ModalService.cs

Changed ModalService events from Action to Func

---

src/Blazored.Modal/BlazoredModalInstance.razor.cs

Disabled rerenders when background click is disabled

---

src/Blazored.Modal/BlazoredModalInstance.razor

Fixed cascaded value to stop unnecessary child component rerenders

---

src/Blazored.Modal/BlazoredModal.razor

Surpressed JSDisconnectException for Blazor Server scenarios

---

src/Blazored.Modal/BlazoredModalInstance.razor
src/Blazored.Modal/Services/IModalService.cs
src/Blazored.Modal/Services/ModalService.cs

Added Show methods without title parameter

---

src/Blazored.Modal/Configuration/ModalParameters.cs

resolves https://github.com/Blazored/Modal/issues/515
stronger type-checking was a bonus add... happy to remove it, if it complicates/muddies things

better support for nulls in ModalParameters + stronger type-checking

---

src/Blazored.Modal/BlazoredModalInstance.razor.css

Swap to CSS grid for position middle

---

src/Blazored.Modal/FocusTrap.razor

Removed markup and logic used for previous debugging
